sudo: false
language: bash
dist: trusty

#before_install:
#    - sudo add-apt-repository -y ppa:deadsnakes/ppa
#    - sudo add-apt-repository -y ppa:openjdk-r/ppa
#    - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9 # To enable cran.r-project.org
#    - echo 'deb http://cran.r-project.org/bin/linux/ubuntu trusty/' | sudo tee -a /etc/apt/sources.list
#    - sudo apt-get -y update 
#    - sudo apt-get -y install r-base
#    - sudo apt-get -y install openjdk-8-jdk
#    - sudo apt-get -y install python3.6-dev
#    - ln -sf `which python3.6` ${PATH%%:*}/python3 # Link python3.6 to python3 and put it first in PATH
#    - wget https://bootstrap.pypa.io/get-pip.py    # Install pip3
#    - python3 get-pip.py --user
#    - easy_install --user pip
#    - mkdir -p ~/R/library && echo '.libPaths(c("~/R/library", .libPaths()))' >> ~/.Rprofile # Pick a writable dir for R packages

script:
    - bash setup.sh --help
    - bash setup.sh
