sudo: false
language: bash
dist: trusty

before_install:
    - sudo "deb http://cloud.r-project.org/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list
    - sudo add-apt-repository -y ppa:deadsnakes/ppa
    - sudo apt-get update -q
    - sudo apt-get -y install python3.6
    - ln -sf `which python3.6` ${PATH%%:*}/python3 
    - python3 --version
    - wget https://bootstrap.pypa.io/get-pip.py 
    - python3 get-pip.py --verbose --user
    - easy_install3 pip
    - pip3 --version || true
    - pip --version || true
    - sudo apt-get -y install gfortran
    - sudo apt-get -y install r-base
    - which R
    - R --version
    - mkdir -p ~/R/library && echo '.libPaths(c("~/R/library", .libPaths()))' >> ~/.Rprofile

script:
    - bash setup.sh --user
