sudo: false
language: bash

addons:
    apt:
        packages:
            - r-base

#before_install:
#    - wget https://www.python.org/ftp/python/3.6.5/Python-3.6.5.tgz
#    - tar xf Python-3.6.5.tgz && cd Python-3.6.5
#    - ./configure --prefix=${HOME} && make && make install
#    - cd ../

script:
    - bash setup.sh --user
