sudo: false
language: bash
dist: trusty

before_install:
    - sudo add-apt-repository -y ppa:deadsnakes/ppa
    - sudo apt-get update -q
    - sudo apt-get -y --purge remove r-base-core
    - sudo apt-get -y install gfortran
    - sudo apt-get -y install r-base
    - sudo apt-get -y install python3.6
    - ln -sf `which python3.6` ${PATH%%:*}/python3 && which python3.6 && ls -l ${PATH%%:*}/
    - sudo apt-get -y install python3-pip 
    - ln -sf `which pip3.6` ${PATH%%:*}/pip3 && which pip3.6 && ls -l ${PATH%%:*}/
    - mkdir -p ~/R/library && echo '.libPaths(c("~/R/library", .libPaths()))' >> ~/.Rprofile

script:
    - bash setup.sh --user
