sudo: false
language: bash
dist: trusty

before_install:
    - sudo add-apt-repository -y ppa:deadsnakes/ppa
    - sudo apt-get update -q
    - which R || true 
    - sudo apt-get -y install gfortran
    - sudo apt-get -y install r-base
    - which R
    - R --version
    - which pip3 || true
    - rm -f `which pip3`
    - sudo apt-get -y install python3.6
    - echo $PATH
    - ln -sf `which python3.6` ${PATH%%:*}/python3 
    - which python3.6 
    - which python3
    - ls -l ${PATH%%:*}/
    - sudo apt-get -y install python3-pip
    - which pip3 || true 
    - which pip || true
    - ls -l /usr/bin/
    - mkdir -p ~/R/library && echo '.libPaths(c("~/R/library", .libPaths()))' >> ~/.Rprofile

script:
    - bash setup.sh --user
