sudo: false
language: bash
dist: xenial

before_install:
    - sudo apt-get update -q
    - sudo apt-get -y install gfortran
    - sudo apt-get -y install r-base
    - sudo apt-get -y install python3
    - mkdir -p ~/R/library && echo '.libPaths(c("~/R/library", .libPaths()))' >> ~/.Rprofile

script:
    - bash setup.sh --user
